# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_control_msgs/Mission.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robot_control_msgs.msg
import std_msgs.msg

class Mission(genpy.Message):
  _md5sum = "4d1e6adeb5b187311718ea244ab2d45a"
  _type = "robot_control_msgs/Mission"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string action
string target
Attributes attributes

================================================================================
MSG: robot_control_msgs/Attributes
# For human target
HumanAttributes human

# For Object target
ObjectAttributes object

# For navigation target
NaviAttributes navi

# For Vision target
VisionAttributes vision

# For speech/speak target
SpeechAttributes speech

================================================================================
MSG: robot_control_msgs/HumanAttributes
string name
string gender
string gesture

================================================================================
MSG: robot_control_msgs/ObjectAttributes
string name
string color


================================================================================
MSG: robot_control_msgs/NaviAttributes
string location

================================================================================
MSG: robot_control_msgs/VisionAttributes
Header header
PixelCoords pixel_coords
SpaceCoords space_coords

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: robot_control_msgs/PixelCoords
int32 pixel_x
int32 pixel_y

================================================================================
MSG: robot_control_msgs/SpaceCoords
float32 x
float32 y
float32 z

================================================================================
MSG: robot_control_msgs/SpeechAttributes
string sentence

"""
  __slots__ = ['action','target','attributes']
  _slot_types = ['string','string','robot_control_msgs/Attributes']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       action,target,attributes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Mission, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.action is None:
        self.action = ''
      if self.target is None:
        self.target = ''
      if self.attributes is None:
        self.attributes = robot_control_msgs.msg.Attributes()
    else:
      self.action = ''
      self.target = ''
      self.attributes = robot_control_msgs.msg.Attributes()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.action
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.human.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.human.gender
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.human.gesture
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.object.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.object.color
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.navi.location
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.attributes.vision.header.seq, _x.attributes.vision.header.stamp.secs, _x.attributes.vision.header.stamp.nsecs))
      _x = self.attributes.vision.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i3f().pack(_x.attributes.vision.pixel_coords.pixel_x, _x.attributes.vision.pixel_coords.pixel_y, _x.attributes.vision.space_coords.x, _x.attributes.vision.space_coords.y, _x.attributes.vision.space_coords.z))
      _x = self.attributes.speech.sentence
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.attributes is None:
        self.attributes = robot_control_msgs.msg.Attributes()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.human.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.human.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.human.gender = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.human.gender = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.human.gesture = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.human.gesture = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.object.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.object.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.object.color = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.object.color = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.navi.location = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.navi.location = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.attributes.vision.header.seq, _x.attributes.vision.header.stamp.secs, _x.attributes.vision.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.vision.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.vision.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.attributes.vision.pixel_coords.pixel_x, _x.attributes.vision.pixel_coords.pixel_y, _x.attributes.vision.space_coords.x, _x.attributes.vision.space_coords.y, _x.attributes.vision.space_coords.z,) = _get_struct_2i3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.speech.sentence = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.speech.sentence = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.action
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.human.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.human.gender
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.human.gesture
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.object.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.object.color
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.attributes.navi.location
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.attributes.vision.header.seq, _x.attributes.vision.header.stamp.secs, _x.attributes.vision.header.stamp.nsecs))
      _x = self.attributes.vision.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i3f().pack(_x.attributes.vision.pixel_coords.pixel_x, _x.attributes.vision.pixel_coords.pixel_y, _x.attributes.vision.space_coords.x, _x.attributes.vision.space_coords.y, _x.attributes.vision.space_coords.z))
      _x = self.attributes.speech.sentence
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.attributes is None:
        self.attributes = robot_control_msgs.msg.Attributes()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.human.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.human.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.human.gender = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.human.gender = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.human.gesture = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.human.gesture = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.object.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.object.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.object.color = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.object.color = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.navi.location = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.navi.location = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.attributes.vision.header.seq, _x.attributes.vision.header.stamp.secs, _x.attributes.vision.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.vision.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.vision.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.attributes.vision.pixel_coords.pixel_x, _x.attributes.vision.pixel_coords.pixel_y, _x.attributes.vision.space_coords.x, _x.attributes.vision.space_coords.y, _x.attributes.vision.space_coords.z,) = _get_struct_2i3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attributes.speech.sentence = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attributes.speech.sentence = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i3f = None
def _get_struct_2i3f():
    global _struct_2i3f
    if _struct_2i3f is None:
        _struct_2i3f = struct.Struct("<2i3f")
    return _struct_2i3f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
