// Generated by gencpp from file robot_vision_msgs/CheckForHumanPosesFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_VISION_MSGS_MESSAGE_CHECKFORHUMANPOSESFEEDBACK_H
#define ROBOT_VISION_MSGS_MESSAGE_CHECKFORHUMANPOSESFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_vision_msgs
{
template <class ContainerAllocator>
struct CheckForHumanPosesFeedback_
{
  typedef CheckForHumanPosesFeedback_<ContainerAllocator> Type;

  CheckForHumanPosesFeedback_()
    {
    }
  CheckForHumanPosesFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CheckForHumanPosesFeedback_

typedef ::robot_vision_msgs::CheckForHumanPosesFeedback_<std::allocator<void> > CheckForHumanPosesFeedback;

typedef boost::shared_ptr< ::robot_vision_msgs::CheckForHumanPosesFeedback > CheckForHumanPosesFeedbackPtr;
typedef boost::shared_ptr< ::robot_vision_msgs::CheckForHumanPosesFeedback const> CheckForHumanPosesFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_vision_msgs/CheckForHumanPosesFeedback";
  }

  static const char* value(const ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback definition\n"
"\n"
;
  }

  static const char* value(const ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckForHumanPosesFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_vision_msgs::CheckForHumanPosesFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_VISION_MSGS_MESSAGE_CHECKFORHUMANPOSESFEEDBACK_H
