# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_group
  joint_model_group_pose: up
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - head_pan_joint
    - head_lift_joint
    - arm_1_F3_joint
    - arm_2_F4_joint
    - arm_3_F4_joint
    - arm_4_F3_joint
    - arm_5_F3_joint
    - arm_6_F3_joint
    - gripper_joint
    - wheel_left_joint
    - wheel_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_1_F3_joint
      - arm_2_F4_joint
      - arm_3_F4_joint
      - arm_4_F3_joint
      - arm_5_F3_joint
      - arm_6_F3_joint
  - name: gripper_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_joint
  - name: head_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - head_pan_joint
      - head_lift_joint
arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_1_F3_joint
    - arm_2_F4_joint
    - arm_3_F4_joint
    - arm_4_F3_joint
    - arm_5_F3_joint
    - arm_6_F3_joint
  gains:
    arm_1_F3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_2_F4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_3_F4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_4_F3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_5_F3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_6_F3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
head_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_pan_joint
    - head_lift_joint
  gains:
    head_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    head_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
