// Auto-generated. Do not edit!

// (in-package robot_vision_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let HumanPoses = require('./HumanPoses.js');

//-----------------------------------------------------------

class CheckForHumanPosesResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.id = null;
      this.human_poses = null;
    }
    else {
      if (initObj.hasOwnProperty('id')) {
        this.id = initObj.id
      }
      else {
        this.id = 0;
      }
      if (initObj.hasOwnProperty('human_poses')) {
        this.human_poses = initObj.human_poses
      }
      else {
        this.human_poses = new HumanPoses();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CheckForHumanPosesResult
    // Serialize message field [id]
    bufferOffset = _serializer.int16(obj.id, buffer, bufferOffset);
    // Serialize message field [human_poses]
    bufferOffset = HumanPoses.serialize(obj.human_poses, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CheckForHumanPosesResult
    let len;
    let data = new CheckForHumanPosesResult(null);
    // Deserialize message field [id]
    data.id = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [human_poses]
    data.human_poses = HumanPoses.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += HumanPoses.getMessageSize(object.human_poses);
    return length + 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_vision_msgs/CheckForHumanPosesResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b5d80e49b1e27164586685518cf7c02e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result definition
    int16 id
    robot_vision_msgs/HumanPoses human_poses
    
    
    ================================================================================
    MSG: robot_vision_msgs/HumanPoses
    Header header
    Header image_header
    # Poses for several people
    HumanPose[] poses
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: robot_vision_msgs/HumanPose
    # Pose for one single person
    uint32 human_id
    string pose
    # Joints
    Joint Nose
    Joint Chest
    Joint RShoulder
    Joint RElbow
    Joint RWrist
    Joint LShoulder
    Joint LElbow
    Joint LWrist
    Joint RHip
    Joint RKnee
    Joint RAnkle
    Joint LHip
    Joint LKnee
    Joint LAnkle
    Joint REye
    Joint LEye
    Joint REar
    Joint LEar
    
    
    ================================================================================
    MSG: robot_vision_msgs/Joint
    # Pixel Coordinates for one single joint
    int16 x
    int16 y
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CheckForHumanPosesResult(null);
    if (msg.id !== undefined) {
      resolved.id = msg.id;
    }
    else {
      resolved.id = 0
    }

    if (msg.human_poses !== undefined) {
      resolved.human_poses = HumanPoses.Resolve(msg.human_poses)
    }
    else {
      resolved.human_poses = new HumanPoses()
    }

    return resolved;
    }
};

module.exports = CheckForHumanPosesResult;
