(cl:defpackage robot_navigation_msgs-msg
  (:use )
  (:export
   "<MOVEROBOTACTION>"
   "MOVEROBOTACTION"
   "<MOVEROBOTACTIONFEEDBACK>"
   "MOVEROBOTACTIONFEEDBACK"
   "<MOVEROBOTACTIONGOAL>"
   "MOVEROBOTACTIONGOAL"
   "<MOVEROBOTACTIONRESULT>"
   "MOVEROBOTACTIONRESULT"
   "<MOVEROBOTFEEDBACK>"
   "MOVEROBOTFEEDBACK"
   "<MOVEROBOTGOAL>"
   "MOVEROBOTGOAL"
   "<MOVEROBOTRESULT>"
   "MOVEROBOTRESULT"
  ))

