// Generated by gencpp from file turtlebot_arm_object_manipulation/ObjectDetectionGoal.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_ARM_OBJECT_MANIPULATION_MESSAGE_OBJECTDETECTIONGOAL_H
#define TURTLEBOT_ARM_OBJECT_MANIPULATION_MESSAGE_OBJECTDETECTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_arm_object_manipulation
{
template <class ContainerAllocator>
struct ObjectDetectionGoal_
{
  typedef ObjectDetectionGoal_<ContainerAllocator> Type;

  ObjectDetectionGoal_()
    : frame()  {
    }
  ObjectDetectionGoal_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetectionGoal_

typedef ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<std::allocator<void> > ObjectDetectionGoal;

typedef boost::shared_ptr< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal > ObjectDetectionGoalPtr;
typedef boost::shared_ptr< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal const> ObjectDetectionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator1> & lhs, const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.frame == rhs.frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator1> & lhs, const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_arm_object_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a054304ca480f0e0c67ec5f261591b09";
  }

  static const char* value(const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa054304ca480f0e0ULL;
  static const uint64_t static_value2 = 0xc67ec5f261591b09ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_arm_object_manipulation/ObjectDetectionGoal";
  }

  static const char* value(const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"\n"
"string frame\n"
"\n"
;
  }

  static const char* value(const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetectionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_arm_object_manipulation::ObjectDetectionGoal_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_ARM_OBJECT_MANIPULATION_MESSAGE_OBJECTDETECTIONGOAL_H
