controller_list:
  - name: fake_arm_group_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
      - gripper_link_joint
  - name: fake_gripper_group_controller
    joints:
      - gripper_joint
initial:  # Define initial robot poses.
  - group: arm_group
    pose: up
  - group: gripper_group
    pose: rest