// Generated by gencpp from file robot_control_msgs/Attributes.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MSGS_MESSAGE_ATTRIBUTES_H
#define ROBOT_CONTROL_MSGS_MESSAGE_ATTRIBUTES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_control_msgs/HumanAttributes.h>
#include <robot_control_msgs/ObjectAttributes.h>
#include <robot_control_msgs/NaviAttributes.h>
#include <robot_control_msgs/VisionAttributes.h>
#include <robot_control_msgs/SpeechAttributes.h>

namespace robot_control_msgs
{
template <class ContainerAllocator>
struct Attributes_
{
  typedef Attributes_<ContainerAllocator> Type;

  Attributes_()
    : human()
    , object()
    , navi()
    , vision()
    , speech()  {
    }
  Attributes_(const ContainerAllocator& _alloc)
    : human(_alloc)
    , object(_alloc)
    , navi(_alloc)
    , vision(_alloc)
    , speech(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robot_control_msgs::HumanAttributes_<ContainerAllocator>  _human_type;
  _human_type human;

   typedef  ::robot_control_msgs::ObjectAttributes_<ContainerAllocator>  _object_type;
  _object_type object;

   typedef  ::robot_control_msgs::NaviAttributes_<ContainerAllocator>  _navi_type;
  _navi_type navi;

   typedef  ::robot_control_msgs::VisionAttributes_<ContainerAllocator>  _vision_type;
  _vision_type vision;

   typedef  ::robot_control_msgs::SpeechAttributes_<ContainerAllocator>  _speech_type;
  _speech_type speech;





  typedef boost::shared_ptr< ::robot_control_msgs::Attributes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control_msgs::Attributes_<ContainerAllocator> const> ConstPtr;

}; // struct Attributes_

typedef ::robot_control_msgs::Attributes_<std::allocator<void> > Attributes;

typedef boost::shared_ptr< ::robot_control_msgs::Attributes > AttributesPtr;
typedef boost::shared_ptr< ::robot_control_msgs::Attributes const> AttributesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control_msgs::Attributes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control_msgs::Attributes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control_msgs::Attributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::Attributes_<ContainerAllocator2> & rhs)
{
  return lhs.human == rhs.human &&
    lhs.object == rhs.object &&
    lhs.navi == rhs.navi &&
    lhs.vision == rhs.vision &&
    lhs.speech == rhs.speech;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control_msgs::Attributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::Attributes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::Attributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::Attributes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::Attributes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::Attributes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::Attributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::Attributes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control_msgs::Attributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dc606c967592d7f4fb27e815eadac7b";
  }

  static const char* value(const ::robot_control_msgs::Attributes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dc606c967592d7fULL;
  static const uint64_t static_value2 = 0x4fb27e815eadac7bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control_msgs::Attributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control_msgs/Attributes";
  }

  static const char* value(const ::robot_control_msgs::Attributes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control_msgs::Attributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# For human target\n"
"HumanAttributes human\n"
"\n"
"# For Object target\n"
"ObjectAttributes object\n"
"\n"
"# For navigation target\n"
"NaviAttributes navi\n"
"\n"
"# For Vision target\n"
"VisionAttributes vision\n"
"\n"
"# For speech/speak target\n"
"SpeechAttributes speech\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/HumanAttributes\n"
"string name\n"
"string gender\n"
"string gesture\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/ObjectAttributes\n"
"string name\n"
"string color\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/NaviAttributes\n"
"string location\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/VisionAttributes\n"
"Header header\n"
"PixelCoords pixel_coords\n"
"SpaceCoords space_coords\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/PixelCoords\n"
"int32 pixel_x\n"
"int32 pixel_y\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/SpaceCoords\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/SpeechAttributes\n"
"string sentence\n"
"\n"
;
  }

  static const char* value(const ::robot_control_msgs::Attributes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control_msgs::Attributes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.human);
      stream.next(m.object);
      stream.next(m.navi);
      stream.next(m.vision);
      stream.next(m.speech);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Attributes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control_msgs::Attributes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control_msgs::Attributes_<ContainerAllocator>& v)
  {
    s << indent << "human: ";
    s << std::endl;
    Printer< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >::stream(s, indent + "  ", v.human);
    s << indent << "object: ";
    s << std::endl;
    Printer< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >::stream(s, indent + "  ", v.object);
    s << indent << "navi: ";
    s << std::endl;
    Printer< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >::stream(s, indent + "  ", v.navi);
    s << indent << "vision: ";
    s << std::endl;
    Printer< ::robot_control_msgs::VisionAttributes_<ContainerAllocator> >::stream(s, indent + "  ", v.vision);
    s << indent << "speech: ";
    s << std::endl;
    Printer< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >::stream(s, indent + "  ", v.speech);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MSGS_MESSAGE_ATTRIBUTES_H
