// Generated by gencpp from file robot_control_msgs/HumanAttributes.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MSGS_MESSAGE_HUMANATTRIBUTES_H
#define ROBOT_CONTROL_MSGS_MESSAGE_HUMANATTRIBUTES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control_msgs
{
template <class ContainerAllocator>
struct HumanAttributes_
{
  typedef HumanAttributes_<ContainerAllocator> Type;

  HumanAttributes_()
    : name()
    , gender()
    , gesture()  {
    }
  HumanAttributes_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , gender(_alloc)
    , gesture(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _gender_type;
  _gender_type gender;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _gesture_type;
  _gesture_type gesture;





  typedef boost::shared_ptr< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> const> ConstPtr;

}; // struct HumanAttributes_

typedef ::robot_control_msgs::HumanAttributes_<std::allocator<void> > HumanAttributes;

typedef boost::shared_ptr< ::robot_control_msgs::HumanAttributes > HumanAttributesPtr;
typedef boost::shared_ptr< ::robot_control_msgs::HumanAttributes const> HumanAttributesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control_msgs::HumanAttributes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control_msgs::HumanAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::HumanAttributes_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.gender == rhs.gender &&
    lhs.gesture == rhs.gesture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control_msgs::HumanAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::HumanAttributes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "766b9e1088bf6904a9780c64efb5654b";
  }

  static const char* value(const ::robot_control_msgs::HumanAttributes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x766b9e1088bf6904ULL;
  static const uint64_t static_value2 = 0xa9780c64efb5654bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control_msgs/HumanAttributes";
  }

  static const char* value(const ::robot_control_msgs::HumanAttributes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string gender\n"
"string gesture\n"
;
  }

  static const char* value(const ::robot_control_msgs::HumanAttributes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.gender);
      stream.next(m.gesture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanAttributes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control_msgs::HumanAttributes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control_msgs::HumanAttributes_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "gender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.gender);
    s << indent << "gesture: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.gesture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MSGS_MESSAGE_HUMANATTRIBUTES_H
