// Generated by gencpp from file robot_control_msgs/Mission.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MSGS_MESSAGE_MISSION_H
#define ROBOT_CONTROL_MSGS_MESSAGE_MISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_control_msgs/Attributes.h>

namespace robot_control_msgs
{
template <class ContainerAllocator>
struct Mission_
{
  typedef Mission_<ContainerAllocator> Type;

  Mission_()
    : action()
    , target()
    , attributes()  {
    }
  Mission_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , target(_alloc)
    , attributes(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_type;
  _target_type target;

   typedef  ::robot_control_msgs::Attributes_<ContainerAllocator>  _attributes_type;
  _attributes_type attributes;





  typedef boost::shared_ptr< ::robot_control_msgs::Mission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control_msgs::Mission_<ContainerAllocator> const> ConstPtr;

}; // struct Mission_

typedef ::robot_control_msgs::Mission_<std::allocator<void> > Mission;

typedef boost::shared_ptr< ::robot_control_msgs::Mission > MissionPtr;
typedef boost::shared_ptr< ::robot_control_msgs::Mission const> MissionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control_msgs::Mission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control_msgs::Mission_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control_msgs::Mission_<ContainerAllocator1> & lhs, const ::robot_control_msgs::Mission_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.target == rhs.target &&
    lhs.attributes == rhs.attributes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control_msgs::Mission_<ContainerAllocator1> & lhs, const ::robot_control_msgs::Mission_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::Mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::Mission_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::Mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::Mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::Mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::Mission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control_msgs::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d1e6adeb5b187311718ea244ab2d45a";
  }

  static const char* value(const ::robot_control_msgs::Mission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d1e6adeb5b18731ULL;
  static const uint64_t static_value2 = 0x1718ea244ab2d45aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control_msgs::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control_msgs/Mission";
  }

  static const char* value(const ::robot_control_msgs::Mission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control_msgs::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n"
"string target\n"
"Attributes attributes\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/Attributes\n"
"# For human target\n"
"HumanAttributes human\n"
"\n"
"# For Object target\n"
"ObjectAttributes object\n"
"\n"
"# For navigation target\n"
"NaviAttributes navi\n"
"\n"
"# For Vision target\n"
"VisionAttributes vision\n"
"\n"
"# For speech/speak target\n"
"SpeechAttributes speech\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/HumanAttributes\n"
"string name\n"
"string gender\n"
"string gesture\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/ObjectAttributes\n"
"string name\n"
"string color\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/NaviAttributes\n"
"string location\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/VisionAttributes\n"
"Header header\n"
"PixelCoords pixel_coords\n"
"SpaceCoords space_coords\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/PixelCoords\n"
"int32 pixel_x\n"
"int32 pixel_y\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/SpaceCoords\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/SpeechAttributes\n"
"string sentence\n"
"\n"
;
  }

  static const char* value(const ::robot_control_msgs::Mission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control_msgs::Mission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.target);
      stream.next(m.attributes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control_msgs::Mission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control_msgs::Mission_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target);
    s << indent << "attributes: ";
    s << std::endl;
    Printer< ::robot_control_msgs::Attributes_<ContainerAllocator> >::stream(s, indent + "  ", v.attributes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MSGS_MESSAGE_MISSION_H
