// Generated by gencpp from file robot_control_msgs/NaviAttributes.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MSGS_MESSAGE_NAVIATTRIBUTES_H
#define ROBOT_CONTROL_MSGS_MESSAGE_NAVIATTRIBUTES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control_msgs
{
template <class ContainerAllocator>
struct NaviAttributes_
{
  typedef NaviAttributes_<ContainerAllocator> Type;

  NaviAttributes_()
    : location()  {
    }
  NaviAttributes_(const ContainerAllocator& _alloc)
    : location(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> const> ConstPtr;

}; // struct NaviAttributes_

typedef ::robot_control_msgs::NaviAttributes_<std::allocator<void> > NaviAttributes;

typedef boost::shared_ptr< ::robot_control_msgs::NaviAttributes > NaviAttributesPtr;
typedef boost::shared_ptr< ::robot_control_msgs::NaviAttributes const> NaviAttributesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control_msgs::NaviAttributes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control_msgs::NaviAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::NaviAttributes_<ContainerAllocator2> & rhs)
{
  return lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control_msgs::NaviAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::NaviAttributes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03da474bc61cfeb81a8854b4ca05bafa";
  }

  static const char* value(const ::robot_control_msgs::NaviAttributes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03da474bc61cfeb8ULL;
  static const uint64_t static_value2 = 0x1a8854b4ca05bafaULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control_msgs/NaviAttributes";
  }

  static const char* value(const ::robot_control_msgs::NaviAttributes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string location\n"
;
  }

  static const char* value(const ::robot_control_msgs::NaviAttributes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NaviAttributes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control_msgs::NaviAttributes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control_msgs::NaviAttributes_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MSGS_MESSAGE_NAVIATTRIBUTES_H
