// Generated by gencpp from file robot_control_msgs/ObjectAttributes.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MSGS_MESSAGE_OBJECTATTRIBUTES_H
#define ROBOT_CONTROL_MSGS_MESSAGE_OBJECTATTRIBUTES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control_msgs
{
template <class ContainerAllocator>
struct ObjectAttributes_
{
  typedef ObjectAttributes_<ContainerAllocator> Type;

  ObjectAttributes_()
    : name()
    , color()  {
    }
  ObjectAttributes_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectAttributes_

typedef ::robot_control_msgs::ObjectAttributes_<std::allocator<void> > ObjectAttributes;

typedef boost::shared_ptr< ::robot_control_msgs::ObjectAttributes > ObjectAttributesPtr;
typedef boost::shared_ptr< ::robot_control_msgs::ObjectAttributes const> ObjectAttributesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b22280075e4ceddc1f3d6e076260f31e";
  }

  static const char* value(const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb22280075e4ceddcULL;
  static const uint64_t static_value2 = 0x1f3d6e076260f31eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control_msgs/ObjectAttributes";
  }

  static const char* value(const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string color\n"
"\n"
;
  }

  static const char* value(const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectAttributes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control_msgs::ObjectAttributes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control_msgs::ObjectAttributes_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MSGS_MESSAGE_OBJECTATTRIBUTES_H
