// Generated by gencpp from file robot_control_msgs/SpeechAttributes.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MSGS_MESSAGE_SPEECHATTRIBUTES_H
#define ROBOT_CONTROL_MSGS_MESSAGE_SPEECHATTRIBUTES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control_msgs
{
template <class ContainerAllocator>
struct SpeechAttributes_
{
  typedef SpeechAttributes_<ContainerAllocator> Type;

  SpeechAttributes_()
    : sentence()  {
    }
  SpeechAttributes_(const ContainerAllocator& _alloc)
    : sentence(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sentence_type;
  _sentence_type sentence;





  typedef boost::shared_ptr< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechAttributes_

typedef ::robot_control_msgs::SpeechAttributes_<std::allocator<void> > SpeechAttributes;

typedef boost::shared_ptr< ::robot_control_msgs::SpeechAttributes > SpeechAttributesPtr;
typedef boost::shared_ptr< ::robot_control_msgs::SpeechAttributes const> SpeechAttributesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator2> & rhs)
{
  return lhs.sentence == rhs.sentence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator1> & lhs, const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ee8e7a1b3ec1e5b34263db750df6246";
  }

  static const char* value(const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ee8e7a1b3ec1e5bULL;
  static const uint64_t static_value2 = 0x34263db750df6246ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control_msgs/SpeechAttributes";
  }

  static const char* value(const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sentence\n"
"\n"
;
  }

  static const char* value(const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechAttributes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control_msgs::SpeechAttributes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control_msgs::SpeechAttributes_<ContainerAllocator>& v)
  {
    s << indent << "sentence: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sentence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MSGS_MESSAGE_SPEECHATTRIBUTES_H
