// Generated by gencpp from file robot_control_msgs/VisionResult.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MSGS_MESSAGE_VISIONRESULT_H
#define ROBOT_CONTROL_MSGS_MESSAGE_VISIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <robot_control_msgs/PixelCoords.h>
#include <robot_control_msgs/SpaceCoords.h>

namespace robot_control_msgs
{
template <class ContainerAllocator>
struct VisionResult_
{
  typedef VisionResult_<ContainerAllocator> Type;

  VisionResult_()
    : header()
    , pixel_coords()
    , space_coords()  {
    }
  VisionResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pixel_coords(_alloc)
    , space_coords(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::robot_control_msgs::PixelCoords_<ContainerAllocator>  _pixel_coords_type;
  _pixel_coords_type pixel_coords;

   typedef  ::robot_control_msgs::SpaceCoords_<ContainerAllocator>  _space_coords_type;
  _space_coords_type space_coords;





  typedef boost::shared_ptr< ::robot_control_msgs::VisionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control_msgs::VisionResult_<ContainerAllocator> const> ConstPtr;

}; // struct VisionResult_

typedef ::robot_control_msgs::VisionResult_<std::allocator<void> > VisionResult;

typedef boost::shared_ptr< ::robot_control_msgs::VisionResult > VisionResultPtr;
typedef boost::shared_ptr< ::robot_control_msgs::VisionResult const> VisionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control_msgs::VisionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control_msgs::VisionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control_msgs::VisionResult_<ContainerAllocator1> & lhs, const ::robot_control_msgs::VisionResult_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pixel_coords == rhs.pixel_coords &&
    lhs.space_coords == rhs.space_coords;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control_msgs::VisionResult_<ContainerAllocator1> & lhs, const ::robot_control_msgs::VisionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control_msgs::VisionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control_msgs::VisionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control_msgs::VisionResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38cc13b05903471baf9469bbcfef1116";
  }

  static const char* value(const ::robot_control_msgs::VisionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38cc13b05903471bULL;
  static const uint64_t static_value2 = 0xaf9469bbcfef1116ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control_msgs/VisionResult";
  }

  static const char* value(const ::robot_control_msgs::VisionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"PixelCoords pixel_coords\n"
"SpaceCoords space_coords\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/PixelCoords\n"
"int32 pixel_x\n"
"int32 pixel_y\n"
"\n"
"================================================================================\n"
"MSG: robot_control_msgs/SpaceCoords\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::robot_control_msgs::VisionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pixel_coords);
      stream.next(m.space_coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control_msgs::VisionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control_msgs::VisionResult_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pixel_coords: ";
    s << std::endl;
    Printer< ::robot_control_msgs::PixelCoords_<ContainerAllocator> >::stream(s, indent + "  ", v.pixel_coords);
    s << indent << "space_coords: ";
    s << std::endl;
    Printer< ::robot_control_msgs::SpaceCoords_<ContainerAllocator> >::stream(s, indent + "  ", v.space_coords);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MSGS_MESSAGE_VISIONRESULT_H
