(cl:in-package robot_vision_msgs-msg)
(cl:export '(HUMAN_ID-VAL
          HUMAN_ID
          POSE-VAL
          POSE
          NOSE-VAL
          NOSE
          CHEST-VAL
          CHEST
          RSHOULDER-VAL
          RSHOULDER
          RELBOW-VAL
          RELBOW
          RWRIST-VAL
          RWRIST
          LSHOULDER-VAL
          LSHOULDER
          LELBOW-VAL
          LELBOW
          LWRIST-VAL
          LWRIST
          RHIP-VAL
          RHIP
          RKNEE-VAL
          RKNEE
          RANKLE-VAL
          RANKLE
          LHIP-VAL
          LHIP
          LKNEE-VAL
          LKNEE
          LANKLE-VAL
          LANKLE
          REYE-VAL
          REYE
          LEYE-VAL
          LEYE
          REAR-VAL
          REAR
          LEAR-VAL
          LEAR
))