; Auto-generated. Do not edit!


(cl:in-package robot_vision_msgs-msg)


;//! \htmlinclude CheckForHumanPosesFeedback.msg.html

(cl:defclass <CheckForHumanPosesFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CheckForHumanPosesFeedback (<CheckForHumanPosesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckForHumanPosesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckForHumanPosesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_vision_msgs-msg:<CheckForHumanPosesFeedback> is deprecated: use robot_vision_msgs-msg:CheckForHumanPosesFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckForHumanPosesFeedback>) ostream)
  "Serializes a message object of type '<CheckForHumanPosesFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckForHumanPosesFeedback>) istream)
  "Deserializes a message object of type '<CheckForHumanPosesFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckForHumanPosesFeedback>)))
  "Returns string type for a message object of type '<CheckForHumanPosesFeedback>"
  "robot_vision_msgs/CheckForHumanPosesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckForHumanPosesFeedback)))
  "Returns string type for a message object of type 'CheckForHumanPosesFeedback"
  "robot_vision_msgs/CheckForHumanPosesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckForHumanPosesFeedback>)))
  "Returns md5sum for a message object of type '<CheckForHumanPosesFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckForHumanPosesFeedback)))
  "Returns md5sum for a message object of type 'CheckForHumanPosesFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckForHumanPosesFeedback>)))
  "Returns full string definition for message of type '<CheckForHumanPosesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckForHumanPosesFeedback)))
  "Returns full string definition for message of type 'CheckForHumanPosesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckForHumanPosesFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckForHumanPosesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckForHumanPosesFeedback
))
